/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*
REMINDERS:
AGREGAR TIMER
AGREGAR MENU DIFICULTAD
FUTURO:
AGREGAR ICONOS Y FUNCIONALIDAD BOTON DERECHO RATON
O UN RADIO BUTTON PARA CAMBIAR A MODO SEÑALAR MINAS
*/
package View;
import buscaminas.Casilla;
import buscaminas.Plano;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.Timer;
/**
 *
 * @author House
 */
public class PrincipalWindow extends javax.swing.JFrame implements ActionListener {
    private Integer contadorMinas = 0;  //Numero de minas
    private Integer numeroCasillas = 0; //Numero de casillas
    private Integer contadorAbiertos = 0;
    private Boolean juegoTerminado = false;
    /**
     * Creates new form PrincipalWindow
     */
    public PrincipalWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public void actionPerformed(ActionEvent e){
        if(!juegoTerminado){ //Lo primero es ver que el juego no haya terminado
            Casilla temp2 = (Casilla)e.getSource();
            if(!temp2.getAbierto()){ //También verificamos que no haya sido abierta ya la casilla
                if(temp2.tieneMina()){ //Verificamos si hay mina en el cuadro
                    panel_juego.colorearDemasMinas();
                    temp2.setBackground(Color.RED);
                    this.contadorAbiertos = 0;
                    juegoTerminado = true;
                    javax.swing.JOptionPane.showMessageDialog(this, "JAJAJAJAJJAJJA PERDISTE!!!!!");
                }else{
                    temp2.setAbierto(true);
                    if(temp2.getMinasAlrededor() != 0){
                        temp2.setText(String.format("%d", temp2.getMinasAlrededor()));
                    }else{
                        panel_juego.descubrirMinasVacias(temp2);
                    }
                    temp2.setBackground(Color.PINK);
                    contadorAbiertos = panel_juego.getCasillasAbiertas();
                    if(numeroCasillas-contadorMinas  == contadorAbiertos){
                        javax.swing.JOptionPane.showMessageDialog(this, "Wow ganaste *aplausos*");
                        juegoTerminado = true;
                    }
                }
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Esa casilla ya esta abierta!! I'm watching you");
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "El juego ya terminó, ya déjalo ir bro :v");
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecera = new javax.swing.JPanel();
        lblFilas = new javax.swing.JLabel();
        lblColumnas = new javax.swing.JLabel();
        columnas = new javax.swing.JTextField();
        filas = new javax.swing.JTextField();
        botonComienzo = new javax.swing.JButton();
        lblCantidadMinas = new javax.swing.JLabel();
        plano1 = new buscaminas.Plano();
        panel_juego = new buscaminas.Plano();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFilas.setText("Filas:");

        lblColumnas.setText("Columnas:");

        columnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnasActionPerformed(evt);
            }
        });

        filas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filasActionPerformed(evt);
            }
        });

        botonComienzo.setText("Comenzar The fucking game!");
        botonComienzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComienzoActionPerformed(evt);
            }
        });

        lblCantidadMinas.setText("Cantidad de Minas:");

        javax.swing.GroupLayout cabeceraLayout = new javax.swing.GroupLayout(cabecera);
        cabecera.setLayout(cabeceraLayout);
        cabeceraLayout.setHorizontalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cabeceraLayout.createSequentialGroup()
                        .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColumnas)
                            .addComponent(lblFilas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(columnas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cabeceraLayout.createSequentialGroup()
                                .addComponent(filas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCantidadMinas, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(botonComienzo))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        cabeceraLayout.setVerticalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilas)
                    .addComponent(filas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadMinas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColumnas)
                    .addComponent(columnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonComienzo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_juego.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout plano1Layout = new javax.swing.GroupLayout(plano1);
        plano1.setLayout(plano1Layout);
        plano1Layout.setHorizontalGroup(
            plano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plano1Layout.createSequentialGroup()
                .addComponent(panel_juego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        plano1Layout.setVerticalGroup(
            plano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plano1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_juego, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plano1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plano1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void columnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnasActionPerformed

    private void filasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filasActionPerformed

    private void botonComienzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComienzoActionPerformed
        iniciar();
        this.paintAll(this.getGraphics());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_botonComienzoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalWindow().setVisible(true);
            }
        });
    }
       //METODO DE INICIO DEL JUEGO
    private void iniciar(){
        juegoTerminado = false;
        panel_juego.removeAll();
        Integer nFilas, nColumnas;

        nFilas = Integer.parseInt(this.filas.getText());
        nColumnas = Integer.parseInt(this.columnas.getText());
        panel_juego.setPlano(nFilas, nColumnas);
        this.panel_juego.setLayout(new java.awt.GridLayout(nFilas,nColumnas));
        this.numeroCasillas = nFilas * nColumnas;
        this.contadorMinas = 0;
        this.contadorAbiertos = 0;
        //Mover estos for a un metodo dentro de plano --REMINDER
        for(int i=0; i<nFilas; i++){
            for(int j=0; j<nColumnas; j++){
                panel_juego.getMatrix()[i+1][j+1] = new Casilla();
                panel_juego.getMatrix()[i+1][j+1].addActionListener(this);          
                if( panel_juego.getMatrix()[i+1][j+1].tieneMina()){
                    this.contadorMinas++;
                    panel_juego.setNumeroDeMinas(contadorMinas);
                }
                
                panel_juego.getMatrix()[i+1][j+1].setVisible(true);
                panel_juego.getMatrix()[i+1][j+1].setFont(new Font("Arial", Font.PLAIN, 10));
               
                panel_juego.add(panel_juego.getMatrix()[i+1][j+1]);
                
            }
        }
        panel_juego.setXY();
        panel_juego.obtenerMinasAlrededor();
        panel_juego.setVisible(true);
        lblCantidadMinas.setText("Cantidad de Minas: "+contadorMinas);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComienzo;
    private javax.swing.JPanel cabecera;
    private javax.swing.JTextField columnas;
    private javax.swing.JTextField filas;
    private javax.swing.JLabel lblCantidadMinas;
    private javax.swing.JLabel lblColumnas;
    private javax.swing.JLabel lblFilas;
    private buscaminas.Plano panel_juego;
    private buscaminas.Plano plano1;
    // End of variables declaration//GEN-END:variables
}
